Roblox/roact

- CHANGELOG.md
- lib/Reconciler.lua
- lib/Reconciler.spec.lua
This closes #14. It allows for the children table passed to `Roact.createElement` to contain boolean values, which will be silently ignored. This enables the use of the pattern `condition and Roact.createElement` - without this patch, if `condition` is `false`, an error is thrown.
> Allow (and ignore) booleans as children of components

- lib/Component.lua
- lib/Component.spec.lua
- lib/Reconciler.lua
This fixes #17. It throws an error when setState is called in the following locations:
* the `init` function of a component
* the `render` function of a component
* any point after the component begins unmounting, **including** within `willUnmount`
The error message:
```
State cannot be set at this point: are you setting state from an init, render, or willUnmount function?
```
Tests are included, yay!
This will probably have a merge conflict with #21; I'll fix it when it happens. This required an edit to `Reconciler` to set the flag to false just before unmounting the component.
> setState sanity checking

- lib/Reconciler.lua
This fixes #19. It adds a prettier error message (with stack trace shown if `Roact.DEBUG_ENABLE` has been called; stack trace is drawn from the new element, not the old one) when reconciliation tries to set a primitive element property to an invalid type (or anything that causes `Reconciler._setRbxProp` to throw).
`Roact.DEBUG_ENABLE` has been called.
```
21:18:47.659 - Failed to set property Size on primitive instance of class Frame
21:18:47.660 - ReplicatedStorage.Roact.Reconciler:456: bad argument #3 to '?' (UDim2 expected, got number)
21:18:47.661 - 
21:18:47.661 - Stack Begin
21:18:47.662 - Script 'ReplicatedStorage.Roact.Core', Line 167 - field createElement
21:18:47.662 - Script 'Players.ProlificLexicon.PlayerGui.LocalScript', Line 13 - method render
21:18:47.664 - Script …
```
> Throw a nicer error when failing to set primitive properties

- docs/pages/lifecycle.md
- lib/Component.lua
- lib/Component.spec.lua
This builds on the discussion from #23 after it was merged. It disallows calling `setState` in *all* lifecycle hooks, not just `willUnmount`. The error message has been changed to reflect this:
```
setState cannot be used currently: are you calling setState within a lifecycle hook?
```
> More setState checks

- lib/Component.lua
- lib/Component.spec.lua
- lib/Core.lua
This fixes #30. It adds a `Roact.None` symbol that, when used in setState, will remove the key from the state.
Usage:
```lua
-- state already contains a value named "value"
self:setState({
value = Roact.None,
})
-- state no longer contains "value"
```
> Remove values from setState

- lib/Component.lua
- lib/Component.spec.lua
This fixes #33. It allows `setState` to accept a function, which is called with the `props` and `state` tables. This function is expected to return a partial state, which is then used to update the component's state.
> Allow functions to be passed to setState

- lib/Component.lua
- lib/Reconciler.lua
- lib/init.spec.lua
Closes #32.
This addresses one usability issue of Roact related to updating components without having to manually expose values like `setState`.
The new API has been an internal API for awhile, and works like this:
```lua
local handle = Roact.reify(Roact.createElement("StringValue", {
Value = "Hello",
}))
-- Previously, we were now stuck with this element and could only tear it down.
-- Now, we can modify it with Roact.reconcile:
handle = Roact.reconcile(handle, Roact.createElement("StringValue", {
Value = "World",
}))
```
One interesting gotcha about the API is that it *takes ownership* of the handle you pass in, and has the potential to return a new one. That means that `reconcile` is free to `teardown` the entire tree that you pass it and construct a new one.
An example that gets a lot …
> Add Reconciler.reconcile to the public API

- docs/api-reference.md
- lib/Core.lua
- lib/Core.spec.lua
- lib/Reconciler.lua
- lib/init.spec.lua
Fixes #45. Moves the various element-type determining functions into `Reconciler` and removes them from the public API.
> Remove is*Element functions

- lib/Component.lua
- lib/Component.spec.lua
Fixes #53.
Adds a static class function, `getDerivedStateFromProps`, that is invoked when a component instance is created and when properties change. This function receives two arguments: `newProps`, the new properties table, and `currentState`, the component's current state (note that in cases where rendering causes both properties and state to change, `currentState` will equal the new state - I'm not sure if this happens in practice).
`getDerivedStateFromProps` may return either a table or `nil`; if it returns a table, the table is merged into the state without triggering another re-render. This is called before any lifecycle hooks invoke, including `willUpdate`.
> Add getDerivedStateFromProps

- lib/Component.lua
- lib/Component.spec.lua
Tiny patch that fixes #63. Unit test added to confirm it works!
> Allow canceling render

- lib/Component.lua
- lib/Reconciler.lua
- lib/invalidSetStateMessages.lua
Fixes #66.
This PR replaces the single "you can't use setState here" message with a bunch of new messages, each tailored to the exact case.
They give much more useful information, and where possible, where to put your `setState` call instead.
It also catches an extra case where the render and reconciliation steps _were not_ being guarded, specifically during reify.
> Introduce much more detailed setState error messages

- lib/init.spec.lua
There were a couple APIs that we were exposing that didn't have tests to validate them.
This changes the `init.spec.lua` API to require that everything we expose is explicit and intentionally exposed.
> Make test for public API more strict

- lib/Component.lua
- lib/Config.lua
- lib/Instrumentation.lua
- lib/Instrumentation.spec.lua
- lib/init.lua
- lib/init.spec.lua
Retrying my approach to tracking performance. This will gather stats about `render` calls and `shouldUpdate` calls, and should be able to provide info that would help indicate when to make a `Component` a `PureComponent` or vice versa, when to write a custom `shouldUpdate`, or when to try to cut down on the complexity of `render` methods.
I didn't find a particularly clean way to inject the instrumentation into the `Component` code without muddling it a bit, so I'd love suggestions for integrating it more gracefully (I left TODOs to this effect).
> Component benchmarks

- README.md
The documentation is inaccurate, and doesn't work.
> Fix readme example. Children are the third argument of createElement().

- CHANGELOG.md
- docs/advanced/refs.md
- docs/api-reference.md
- lib/Reconciler.lua
- lib/Reconciler.spec.lua
- lib/createRef.lua
- lib/createRef.spec.lua
- lib/init.lua
- lib/init.spec.lua
Closes #70.
Adds a `createRef` function to the global Roact namespace. `createRef` returns an object reference with a `current` property that can be used like existing functional refs. Example usage:
```lua
local SomeTextbox = Roact.Component:extend("SomeTextbox")
function SomeTextbox:init()
self.textboxRef = Roact.createRef()
end
function SomeTextbox:render()
return Roact.createElement("TextBox", {
-- ...
[Roact.Ref] = self.textboxRef
})
end
function SomeTextbox:didMount()
self.textboxRef.current:CaptureFocus()
end
```
> createRef API

- CHANGELOG.md
- docs/api-reference.md
- lib/Component.lua
- lib/Component.spec.lua
Closes #81. Adds a `stackTrace` method to `Component` that returns the current stack trace for the instance. This will return `nil` when `elementTracing` is `false`.
> Add stackTrace getter

- CHANGELOG.md
- lib/Reconciler.lua
This is a minor change that ideally shouldn't be user-visible.
Before #92, there was a bug in Roact where when refs were updated, nothing would happen. There was a typo in the reconciler code that resulted in the comparison in the reconciler always determining that refs never changed!
After #92, an issue was unveiled by @ZoteTheMighty via some internal Roact code that means that with the typical use of a ref:
```lua
[Roact.Ref] = (rbx)
self.foo = rbx
end
```
...there is a period of time where `self.foo` will be `nil` when Roact nullifies the old ref, makes changes, and then passes the same object to the new ref, since by function identity it changed. This doesn't affect code that keeps a stable ref function, and is only visible to code that acts on a ref in response to a change event. …
> Change refs in one pass, making switching refs atomic

- docs/advanced/refs.md
- docs/api-reference.md
Promote the createRef api to be the more favored mode of ref creation, provide further warnings about the function version.
> Docs: highlight createRef over function-style ref

- lib/Reconciler.lua
Changed comment amount names not affecting anything and being used solely for debugging to mention how the reconciler assumes elements with the same name/key between reconciles are old/new versions of the same element.
> Edited misleading name comment in reconciler

- lib/Component.lua
- lib/Component.spec.lua
- lib/createElement.lua
Fixed bug with defaultProps not being included in newProps when passed into component's shouldUpdate method, causing components to rerender when unnecessary
> Resolved PureComponent render issue when using defaultProps

- lib/Component.lua
This code felt like a potential pitfall if one branch was modified but the other left untouched.
No functionality change should be observed.
> Remove duplicated code in instrumentation checks

- lib/init.lua
The dynamic construction of the Roact API has been problematic for awhile. It's really difficult for type inference to pick up the shape of the API, and it's harder to tell at a glance what all of the functions we export are.
This should not be a user-facing change, has not affected tests, and in general should be seamless.
> Refactor init to explicitly lay out APIs instead of being dynamic

- lib/SingleEventManager.lua
- lib/SingleEventManager.spec.lua
This PR should make SingleEventManager a little bit tidier. Instead of indexing by string keys, the internal event table is indexed by the event objects themselves.
Additionally, this refactored `SingleEventManager` uses an indirection trick to make replacing an existing connection much quicker. When connecting to an event that's already connected, we can just update a member in a table instead of disconnect/reconnecting a signal.
This PR relies on the idea that `GetPropertyChangedSignal` will always return the same signal every time it's called, since we use it for object identity.
> Refactor SingleEventManager

- CHANGELOG.md
- lib/Config.lua
- lib/Reconciler.lua
Closes #88.
This will throw a warning during reconciliation if a component type has changed. It will output stack traces of the two components involved, old and new. In cases where these warnings are unwelcome, they can be disabled by setting the configuration key `warnOnTypeChange` to `false` (defaults to `true`).
* Test changes aren't feasible
* No documentation changes made
> Warn on element type change

- docs/advanced/refs.md
The current guide page is kind of a jumble between functional and object refs.
I tried to make it more clear by focusing on introducing object refs and moving function refs to be basically a footnote.
* ~Added entry to `CHANGELOG.md`~
* ~Added/updated relevant tests~
> Rewrite Ref page in advanced guide

- CHANGELOG.md
- docs/api-reference.md
- lib/Component.lua
- lib/Component.spec.lua
Closes #153.
Rolls back the changes to `Component` that allowed `setState` to be called during `willUpdate` . This helps avoid some edge cases in state updates where correct behavior was difficult to determine.
> Roll back changes that allowed setState to be called inside willUpdate

- lib/RobloxRenderer.lua
- lib/SingleEventManager.lua
- lib/SingleEventManager.spec.lua
Events for the new reconciler :tada:
Host virtual nodes will start handling events whenever an event is first used in the virtual node. If your node is static and has no events in its lifecycle, the event machinery is never set up. Events won't be fired at all during the initial mount process; any events fired in the middle of subsequent updates are queued and fired after the update is completed.
* Documentation updates aren't necessary, since this feature's already documented!
> WIP: Events for new reconciler

- CHANGELOG.md
- lib/Config.lua
This change reflects our growing uncertainty about this being a valid warning in the first place.
* ~~Added/updated relevant tests~~
> Change the default value for warnings on element type changes to 'false'

- lib/assertDeepEqual.lua
- lib/assertDeepEqual.spec.lua
This bit me while I was trying to write tests for something else. I suppose now is a good time to write tests for assertDeepEqual...
> New Reconciler: Fix scary bug in assertDeepEqual (testing utility)

- lib/Component.spec/context.spec.lua
- lib/createReconciler.lua
Discovered this issue in the new reconciler when pointing it at a large existing project.
Context was not being carried over during an update if the component rendered with a given key was changed to a new component type (a case in which we currently warn, but expect everything to work fine).
Writing a regression test for this should be pretty straightforward, but requires several steps.
> New Reconciler: Fix case where context is not passed.

- lib/RobloxRenderer.lua
- lib/createReconciler.lua
This fixes a compatibility issue between the old and new reconcilers, and also allows some more flexibility. It also changes the default tree root name from Foo to RoactTree.
Before this patch, the new reconciler would not allow elements to have a numerical key, which caused problems when mapping an array to children, or similar use cases. Now, values of any type are allowed for element keys; they will be converted to a string in the Roblox renderer.
This also allows increased flexibility for components that add (or modify) the children they receive. As an example, a ScrollingFrame component might want to add a list layout object to its children. To do this, it has to alter `props[Roact.Children]` to add it, and with that comes the possibility that an existing child might be clobbered: …
> Allow any key type for element keys

- lib/createReconciler.lua
Discovered this issue in the new reconciler when pointing it at a large existing project.
When we return a boolean as an element, mounting it will result in a nil virtual node. This is by design, but the `updateVirtualNodeChildren` function fails to account for it. Maybe there's a better place to account for this, or it can be resolved by updating depth information elsewhere?
Additionally, the `replaceVirtualNode` case doesn't appear to be technically possible, because it should always short-circuit beforehand.
~~I haven't yet written a regression test for this, but it should boil down to rendering an element tree in which a node below the root resolves to a boolean.~~
This is a pain to do with the NoopRenderer, and it feels weird to use the RobloxRenderer just to test the regression …
> New Reconciler: Fix possible error when processing boolean element

- lib/ChildUtils.lua
- lib/ChildUtils.spec.lua
- lib/Component.lua
- lib/ElementUtils.lua
- lib/ElementUtils.spec.lua
- lib/RobloxRenderer.lua
- lib/Type.lua
- lib/createFragment.lua
- lib/createReconciler.lua
- lib/createReconciler.spec.lua
Closes #7 (for the new reconciler).
I started from the `new-reconciler-fragments` branch that @LPGhatguy made and finished repairing/adding tests and patching inconsistencies.
One thing that fell out of this change was the need to distinguish between these two scenarios:
1. Updating a virtual node's children from a list of new children
1. This is done by the `RobloxRenderer` to process the children of host nodes, and also the reconciler itself to process children specified via `Roact.Children`.
2. The children are expected to be in the form of a table.
2. Updating a virtual node's children with the result of rendering a component.
1. This is done by `Component` with its lifecycle methods, and also by the reconciler itself to mount/update function components.
2. The expected format is …
> WIP: Fragments for new reconciler

- CHANGELOG.md
- docs/advanced/fragments.md
- docs/api-reference.md
- lib/init.lua
- mkdocs.yml
Follows up #172
Rough draft of some documentation for fragments. This example may not be particularly clear, and more examples or explanations are probably needed.
* ~Added/updated relevant tests~
> New rec document fragments

- lib/createReconciler.lua
Removes the warning when a component's type changes. We've found some very valid use cases for this, and the warning doesn't make much sense in light of them.
> Remove type change warning

- lib/Component.lua
- lib/Component.spec/validateProps.spec.lua
- lib/Config.lua
- lib/createSpy.lua
Supersedes #94; closes #24. Functionally the same as #94, but for the new reconciler instead! Briefly, this adds a new static method to components:
```
static validateProps(props: table) -> (false, message: string) | true
```
Every time props are updated, `validateProps` will be called with the new props before `shouldUpdate` and `init` are called. `validateProps` returns the same parameters that `assert` expects: a boolean, true if the props passed validation, false if they did not, plus a message explaining why they failed. If the first return value is true, the second value is ignored.
This is intended to be used with a type checking library like [PropTypes](https://github.com/AmaranthineCodices/rbx-prop-types) or [t](https://github.com/osyrisrblx/t).
One question remains about this: …
> validateProps for new reconciler

- lib/RobloxRenderer.lua
Fixes an issue found recently with my changes to `RobloxRenderer` to use `xpcall`
* ~~Added/updated relevant tests~~
> Fix error messages from setting invalid props

- CHANGELOG.md
- lib/Component.lua
- lib/Component.spec.lua
- lib/Reconciler.lua
- lib/Reconciler.spec.lua
- lib/ReconcilerCompat.lua
- lib/init.lua
- lib/init.spec.lua
As a step to trying to make user's code more compatible in preparation for `new-reconciler` merging back in, this PR deprecates `Roact.reconcile` in favor of `Roact.update`, which is more clear.
`Roact.reconcile` was already deprecated in the `new-reconciler` branch awhile ago. 
* ~Added/updated documentation~ (#193)
> Deprecate Roact.reconcile in favor of Roact.update in master

- CHANGELOG.md
- lib/init.lua
- lib/init.spec.lua
This PR removes two undocumented APIs that aren't very useful and aren't present in the `new-reconciler` branch.
- `Roact.getGlobalConfigValue`, which let users read the current global configuration. I think we introduced this to try to allow for user-land property validation, but that didn't pan out.
- `Roact.Element`, which lets users figure out whether something is a Roact element. We should re-introduce a typechecking API like the internal one in `new-reconciler`.
* ~Added/updated documentation~ hah, documentation
> Remove undocumented APIs `getGlobalConfigValue` and `Element`

- docs/api-reference.md
GetPropertyChangedSignal does not pass the new value of the property to the function and the Roact.Change handler doesn't add this functionality so the current example code is slightly misleading.
> Change misleading code in Roact.Change example

- lib/createReconciler.lua
- lib/createReconciler.spec.lua
Better not to let people depend on internals.
> Hide tree internals

- docs/advanced/bindings-and-refs.md
- docs/api-reference.md
- examples/ref/init.lua
- lib/createRef.spec.lua
Changes docs around ref to prefer `getValue` method over the `current` field, mentions `ref.current` as deprecated and explains that it cannot be assigned to.
Additionally, add a test to confirm that ref.current == ref:getValue()
> Bless ref:getValue(), update version numbers in docs

- lib/RobloxRenderer.lua
- lib/SingleEventManager.lua
- lib/SingleEventManager.spec.lua
Restores event suspension, which was removed by setState suspension (#183). We're reintroducing this behavior because events can fire while updating properties, which allows you to observe the Roblox instance in an intermediate state that you _probably_ don't want to be doing any calculations on.
> Restore event suspension

- docs/guide/state-and-lifecycle.md
Closes (ISSUES HERE).
*Put your pull request body here!*
> updated example to correctly increment currenttime

- CHANGELOG.md
- src/RobloxRenderer.lua
- src/RobloxRenderer.spec.lua
Closes #209. In ea822f62ec11be3f979344cc34e03b81e48b0b53 we introduced an optimization in RobloxRenderer that avoids calling into the reconciler to update children if the element's children are `nil`. This introduced #209, where when updating a tree with an element that has `nil` children (not an empty table), the existing children are not unmounted.
> Remove children when updating a host node to an element with nil children

- CHANGELOG.md
- docs/api-reference.md
- docs/extra.css
- src/Binding.lua
- src/Binding.spec.lua
- src/init.lua
- src/init.spec.lua
Inspired by #204. 😄 
Reworks bindings from the ground up and adds support for joining bindings together.
> Refactor bindings, introducing joinBindings

- CHANGELOG.md
- src/ElementKind.lua
- src/ElementUtils.lua
- src/ElementUtils.spec.lua
- src/RobloxRenderer.spec.lua
- src/Type.lua
- src/createFragment.lua
- src/createFragment.spec.lua
- src/createReconciler.lua
- src/createReconciler.spec.lua
Closes #205
Fragments can now be used directly as children of a component:
```lua
local function component()
return Roact.createElement("Frame", {}, {
fragments = Roact.createFragment({
A = Roact.createElement("Frame", {}, {})
})
})
end
```
Turning Fragments into Elements make them have their own virtual node, so they can be reconciled as any other nodes.
I'm not so sure about how to write good tests for that, let me know what's the best way (not sure where to assert exactly).
> Make Fragment an Element

- src/createReconciler.lua
Since Fragment is an ElementKind and no longer a Type the check should have been removed in my last pull request.
Let me know if the order `Type.Element`, `nil` and `boolean` is what's best.
Closes #200.
*Put your pull request body here!*
> Reorder render result checks and fix bug

- src/Binding.spec.lua
Fixes a test that may fail if not run with the `bin/spec.lua` test runner. The tests depend on having the `typeChecks` global config value set to true, but did not express this dependency as written.
> Fix tests that depend on specific config values to use the "scoped" feature

- benchmarks.project.json
- benchmarks/hello.bench.lua
- benchmarks/update.bench.lua
- bin/bench.lua
Benchmarks could neither be run from the command line nor from the place generated from place.project.json
1) Habitat:loadFromFs does not know to create a module script when loading a folder with an init.server.lua in it
2) Each benchmark assumed it lived relative to Roact which is not necessarily true - in place.project.json the benchmarks live in ServerScriptService so that that are run automatically
1) Load the init file directly so that we get a module script to require, and not a folder
2) Always look to replicated storage when looking for Roact in the context of a benchmark
Observed that benchmarks ran via
lua bin/bench.lua
rojo build place.project.json -o RoactTestPlace.rbxlx --> open and click play
> Fix benchmarks

- CHANGELOG.md
- src/Component.lua
- src/Component.spec/getDerivedStateFromProps.spec.lua
In Roact 1.x, `setState` is allowed during a component's `init` method. This change was made to unify all state changes and to further discourage direct mutation of state.
However, `getDerivedStateFromProps` remains an ever-present source of finicky corner cases. In the case that users were still assigning directly to state, they would actually lose any _derived_ state that was supposed to be present by the time they rendered.
This actually breaks existing components migrating from Roact 0.2.0 to Roact 1.x. This change addresses that incompatibility.
> Fix inconsistent behavior between setState in init and directly assigning to state

- bin/run-tests.server.lua
- bin/test-roblox-cli.sh
At Roblox, we have an internally utility that's a command line version of Roblox. For people that can use it, it's preferable to use roblox-cli instead of Lemur because of easier setup and improved accuracy.
We'll still be maintaining Lemur as the source of truth for CI builds for the foreseeable future, and this PR does not break running tests under Lemur.
> Add support for running tests via Roblox CLI

- src/Component.lua
- src/Component.spec/context.spec.lua
- src/Component.spec/legacyContext.spec.lua
- src/RobloxRenderer.spec.lua
- src/createReconciler.lua
Works towards #4. This is a prerequisite for the new _public_ Context API proposed in #246.
This change introduced two new methods to the `Component` API:
* `Component:__addContext(key, value)` - Adds a new entry to the context table. This will be available to this component and all of its children, and is intended to be used in a Provider component.
* `Component:__getContext(key)` - Retrieves the context value for the given key. This intended to be used by a Consumer component.
This interface allows us to avoid defensive copying, as even internal Component APIs do not get direct access to the context table. The legacy context API is still present and usable, and will not be affected by these changes.
* ~~Added entry to `CHANGELOG.md`~~ (this should come with …
> New internal Context API

- .github/workflows/deploy-docs.yml
Closes #121.
This uses the same workflow file that @MagiMaster used to auto-deploy our Lua style guide.
> Use workflow to deploy MkDocs documentation

- docs/advanced/context.md
- docs/api-reference.md
- docs/extra.css
Fixes #207. Fixes #241.
This PR documents the new context API (#4) that was recently merged while cleaning up some of the little problems about our docs.
* Changed `<hr>` tags to be solid lines instead of dashed ones (#207)
* Added extra `static` notice to `validateProps` (#241)
* Removed custom CSS in favor of using [Admonition](https://squidfunk.github.io/mkdocs-material/extensions/admonition/)
* Added baseline documentation for the new context feature
> Document new context API and fix some docs mishaps

- docs/api-reference.md
Closes #257 
In the API Documentation on Context, the link to advance concepts is broken #257
> Fix "advance concepts" link in docs

- src/createContext.lua
- src/createContext.spec.lua
Closes #259.
This PR tries to fix the update tearing behavior I discovered and reported in #259 based on a solution that my team has been discussing. I introduced a fairly small and robust test that is currently failing to indicate the problem with our current state and the quick-fix solutions to this problem.
Context values are no longer based on bindings and now instead use a small cell that contains a value and an update signal.
Providers now update context values in two passes:
1. In `willUpdate`, the provider updates the value of the context entry but do not fire any signals. This should cause downstream consumers to be able to immediately read the new value on their next render. Their next render will occur immediately unless an intermediate component implements `shouldUpdate`.
2. …
> Fix prop-context update tearing

- src/createContext.lua
- src/createContext.spec.lua
I discovered a problem with context where consumers that accepted a nil context value would have errors thrown whenever they get re-erendered. This fixes that issue with a simple nil check. likely just an oversight.
> Fix missing nil check in context logic

- .github/workflows/clabot.yml
- CHANGELOG.md
- src/Component.lua
- src/Component.spec/validateProps.spec.lua
Add componentName to property validation error message. This would be helpful in cases where element tracing is not turned on or provides an unhelpful error message.
> Add component name to property validation error message

- .github/workflows/deploy-docs.yml
The newer version of the action should deploy with a newer version of mkdocs-material, which should support the color scheme change in #290.
> Update docs deploy to use a newer GH action

- CHANGELOG.md
- src/createReconciler.lua
Luau started working for me and it caught this so I decided I'd open a quick PR to fix it.
> Fix usage of error() in createReconciler.lua

- CHANGELOG.md
- docs/api-reference.md
Fixes the `Roact.forwardRef` description which is currently`Roact.createRef` instead.
> Fix Roact.forwardRef description

- .luacheckrc
- bin/run-tests.server.lua
- bin/spec.lua
- place.project.json
- src/RobloxRenderer.spec.lua
TestEZ submodule has been updated to latest.
The usage of `CoreGui` was throwing permission errors when running tests within Studio so I've replaced it with a Folder instance in ReplicatedStorage. Since I've updated TestEZ, I was able to use `beforeEach` and `afterEach` to clean up that instance.
> Update TestEZ and fix tests so they work in studio

- CHANGELOG.md
- src/createContext.lua
- src/createContext.spec.lua
Closes #319.
PR #315 uncovered that willUnmount can be called more than once in certain cases. This PR adds a test that demonstrate the problem and fixes it.
> Fix bug in context consumers

- docs/api-reference.md
Fixed Broken link for GetPropertyChangedSignal.
> Fix broken link for GetPropertyChangedSignal

- src/Config.lua
- src/RobloxRenderer.spec.lua
- src/createReconciler.lua
We have had this turned on in a few projects for the last few months and it has proven sound. Remove tempFixUpdateChildrenReEntrancy so it is fixed by default.
> Remove tempFixUpdateChildrenReEntrancy

- .github/workflows/ci.yml
- .github/workflows/deploy-docs.yml
This change updates several non-cached GHA third party actions to use Roblox-ActionsCache. It's a manually created duplicate of #363 to avoid issues with batch changes triggering the CLA.
Closes #363.
> Update GHA non-cached third party actions

- .github/workflows/ci.yml
This batch change updates the reference to the `setup-foreman` action to use the current location of the action in the Roblox org. This should be a no-op, or may fix currently-broken CI.
Please refer to [confluence](https://confluence.rbx.com/display/ENGEFF/Removal+of+grandfathered+3rd-party+GitHub+Actions) for more information.
[_Created by Sourcegraph batch change `pdoyle/migrate-setup-foreman-action`._](https://sourcegraph.rbx.com/users/pdoyle/batch-changes/migrate-setup-foreman-action)
> Update setup-foreman action path

- .github/workflows/ci.yml
- .luaurc
- CHANGELOG.md
- foreman.toml
- src/Binding.lua
- src/Component.lua
- src/ElementUtils.lua
- src/Symbol.lua
- src/Symbol.spec.lua
- src/assertDeepEqual.lua
- src/assign.spec.lua
- src/createReconciler.lua
- src/createReconciler.spec.lua
- src/init.spec.lua
- src/strict.lua
- testez.d.lua
This sets up the repo with Luau analysis and fixes the initial type errors
> Setup basic Luau analysis
